version: "3.7"
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    network_mode: "host"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar

  db:
    image: postgres:latest
    container_name: sonarqube_db
    network_mode: "host"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

  scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar-scanner
    volumes:
      - .:/usr/src
    network_mode: "host"
    depends_on:
      - sonarqube
