name: Build and Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: NPM install and build
      run: |
        npm install
        npm run build
      env:
        VITE_MICROSOFT_AD_CLIENT_ID: ${{ secrets.MICROSOFT_AD_CLIENT_ID }}
        VITE_MICROSOFT_AD_TENANT_ID: ${{ secrets.MICROSOFT_AD_TENANT_ID }}
        VITE_URL: ${{ secrets.URL }}
        VITE_BACKEND_URL: ${{ secrets.BACKEND_URL }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: |
        aws s3 sync dist s3://healthpanel.db1.com.br --delete
      env:
        AWS_DEFAULT_REGION: us-east-1

